//
//  SFSymbolEnum.swift
//  LinkPalm
//
//  Created by Denis Ureke on 2024-02-11.
//

import Foundation

enum SFSymbolEnum: String, CaseIterable, Codable, Hashable {
    case house = "house"
    case heart = "heart"
    case person = "person"
    case clock = "clock"
    case bell = "bell"
    case envelope = "envelope"
    case gear = "gear"
    case trash = "trash"
    case pencil = "pencil"
    case bookmark = "bookmark"
    case camera = "camera"
    case message = "message"
    case phone = "phone"
    case photo = "photo"
    case video = "video"
    case map = "map"
    case airplane = "airplane"
    case car = "car"
    case leaf = "leaf"
    case mail = "mail"
    case newspaper = "newspaper"
    case drop = "drop"
    case flame = "flame"
    case cloud = "cloud"
    case snow = "snow"
    case icloud = "icloud"
    case paperclip = "paperclip"
    case thermometer = "thermometer"
    case umbrella = "umbrella"
    case none = ""
}

enum Emojis: String, CaseIterable, Hashable, Codable {
    case smile = "😀"
    case laugh = "😂"
    case heart = "❤️"
    case crying = "😢"
    case clapping = "👏"
    case thumbsUp = "👍"
    case thumbsDown = "👎"
    case flame = "🔥"
    case star = "⭐"
    case exclamation = "❗"
    case question = "❓"
    case eyes = "👀"
    case sunglasses = "😎"
    case lightning = "⚡"
    case bomb = "💣"
    case peace = "✌️"
    case angry = "😠"
    case mindBlown = "🤯"
    case party = "🥳"
    case sick = "🤒"
    case money = "💰"
    case monkey = "🙈"
    case panda = "🐼"
    case pizza = "🍕"
    case cake = "🍰"
    case basketball = "🏀"
    case soccer = "⚽"
    case guitar = "🎸"
    case airplane = "✈️"
    case rocket = "🚀"
    case wave = "👋"
    case facepalm = "🤦"
    case unicorn = "🦄"
    case taco = "🌮"
    case hamster = "🐹"
    case none = ""
}
